### ISSUE TITLE
Rpi Bridge interface is always down Failed to start systemd-networkd-wait-online.service - Wait for Network to be Configured.

### ISSUE THREAD

**Issue by karneaud** [0rax/BerryOS#25]
I'm using your OS on my RPi4B and configured my network-config as follows:

```
version: 2
ethernets
  eth0:
    dhcp4: false
    dhcp6: false
renderer: networkd
wifis:
  wlan0:
    dhcp4: false
    mode: ap
    band: 5GHz
bridges:
  br0:
    dhcp4: yes
    interfaces:
      - eth0
      - wlan0
    addresses:
      - 192.168.1.1/24
    parameters:
      stp: false
      forward-delay: 0
```

However, when booting in this interface is down and the et0 is initialized with  ipv4

Also when I boot I get this error happening:-

> Dec 14 14:09:46 raspberrypi systemd[1]: Starting systemd-networkd-wait-online.service - Wait for Network to be Configured...
> Dec 14 14:12:04 raspberrypi systemd-networkd-wait-online[572]: Timeout occurred while waiting for network connectivity.
> Dec 14 14:12:04 raspberrypi systemd[1]: systemd-networkd-wait-online.service: Main process exited, code=exited, status=1/FAILURE
> Dec 14 14:12:04 raspberrypi systemd[1]: systemd-networkd-wait-online.service: Failed with result 'exit-code'.
> Dec 14 14:12:04 raspberrypi systemd[1]: Failed to start systemd-networkd-wait-online.service - Wait for Network to be Configured.

I had to update and upgrade the pi 

> Linux raspberrypi 6.6.62+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.62-1+rpt1 (2024-11-25) aarch64 GNU/Linux

and installed `nmtui` and `nmcli` as I was trying to take an easier approach to setting things up.

Would you be able to atleast shed some insight as to why ad least the br0 is booted disabled and defaulting to eth0?
